-- =========================================
-- SNOWFLAKE SETUP FOR MARKET ANALYTICS
-- =========================================

-- Create database FIRST
CREATE DATABASE IF NOT EXISTS MARKET_ANALYTICS;

-- THEN use it
USE DATABASE MARKET_ANALYTICS;

-- Create warehouse
CREATE WAREHOUSE IF NOT EXISTS ANALYTICS_WH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE
COMMENT = 'Warehouse for analytics workloads';

USE WAREHOUSE ANALYTICS_WH;

-- Create schemas
CREATE SCHEMA IF NOT EXISTS RAW;
CREATE SCHEMA IF NOT EXISTS STAGING;
CREATE SCHEMA IF NOT EXISTS MARTS;
CREATE SCHEMA IF NOT EXISTS ML;

-- =========================================
-- RAW TABLES (from Delta Lake)
-- =========================================

-- Fact: Stock Trades
CREATE TABLE IF NOT EXISTS RAW.STOCK_TRADES (
    SYMBOL VARCHAR(20),
    TIMESTAMP_PARSED TIMESTAMP_NTZ,
    TRADE_DATE DATE,
    SECTOR VARCHAR(50),
    EXCHANGE VARCHAR(20),
    CURRENCY VARCHAR(10),
    PRICE FLOAT,
    VOLUME BIGINT,
    PRICE_CHANGE FLOAT,
    PRICE_CHANGE_PCT FLOAT,
    IS_ANOMALY BOOLEAN,
    IS_PRICE_SPIKE BOOLEAN,
    IS_HIGH_VOLUME BOOLEAN,
    PRICE_DIRECTION VARCHAR(10),
    VOLATILITY FLOAT,
    SOURCE VARCHAR(50),
    LOADED_AT TIMESTAMP_NTZ
);

-- Fact: OHLC Candles
CREATE TABLE IF NOT EXISTS RAW.OHLC_CANDLES (
    SYMBOL VARCHAR(20),
    WINDOW_START TIMESTAMP_NTZ,
    WINDOW_END TIMESTAMP_NTZ,
    SECTOR VARCHAR(50),
    EXCHANGE VARCHAR(20),
    CURRENCY VARCHAR(10),
    OPEN FLOAT,
    HIGH FLOAT,
    LOW FLOAT,
    CLOSE FLOAT,
    VOLUME BIGINT,
    AVG_PRICE FLOAT,
    TICK_COUNT INT,
    MAX_CHANGE_PCT FLOAT,
    MIN_CHANGE_PCT FLOAT,
    ANOMALY_COUNT INT,
    CANDLE_COLOR VARCHAR(10),
    CANDLE_RANGE_PCT FLOAT,
    LOADED_AT TIMESTAMP_NTZ
);

-- Fact: Stock with Sentiment
CREATE TABLE IF NOT EXISTS RAW.STOCK_SENTIMENT (
    SYMBOL VARCHAR(20),
    TIMESTAMP_PARSED TIMESTAMP_NTZ,
    PRICE FLOAT,
    PRICE_CHANGE_PCT FLOAT,
    NEWS_SENTIMENT FLOAT,
    NEWS_COUNT INT,
    POSITIVE_NEWS_COUNT INT,
    NEGATIVE_NEWS_COUNT INT,
    LOADED_AT TIMESTAMP_NTZ
);

-- Dimension: Stocks
CREATE TABLE IF NOT EXISTS RAW.DIM_STOCKS (
    SYMBOL VARCHAR(20) PRIMARY KEY,
    NAME VARCHAR(100),
    SECTOR VARCHAR(50),
    EXCHANGE VARCHAR(20),
    CURRENCY VARCHAR(10),
    IS_CURRENT BOOLEAN,
    VALID_FROM TIMESTAMP_NTZ,
    VALID_TO TIMESTAMP_NTZ
);

-- ML Features
CREATE TABLE IF NOT EXISTS ML.FEATURES (
    SYMBOL VARCHAR(20),
    TIMESTAMP_PARSED TIMESTAMP_NTZ,
    PRICE FLOAT,
    PRICE_CHANGE_PCT FLOAT,
    PRICE_MA_5 FLOAT,
    PRICE_MA_10 FLOAT,
    PRICE_MA_20 FLOAT,
    PRICE_STD_5 FLOAT,
    PRICE_STD_10 FLOAT,
    MOMENTUM_5 FLOAT,
    PRICE_CHANGE_PCT_1 FLOAT,
    RSI FLOAT,
    BB_POSITION FLOAT,
    VOLUME BIGINT,
    VOLUME_RATIO FLOAT,
    SENTIMENT_SCORE FLOAT,
    NEWS_COUNT INT,
    HOUR INT,
    DAY_OF_WEEK INT,
    IS_MARKET_OPEN_HOUR INT,
    TARGET INT,
    PRICE_NEXT FLOAT
);

-- ML Predictions
CREATE TABLE IF NOT EXISTS ML.PREDICTIONS (
    SYMBOL VARCHAR(20),
    TIMESTAMP_PARSED TIMESTAMP_NTZ,
    PRICE FLOAT,
    PREDICTION INT,
    PREDICTION_LABEL VARCHAR(10),
    PROBABILITY_DOWN FLOAT,
    PROBABILITY_UP FLOAT,
    CONFIDENCE FLOAT,
    ACTUAL INT,
    CORRECT BOOLEAN,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- =========================================
-- GRANT PERMISSIONS
-- =========================================

GRANT USAGE ON DATABASE MARKET_ANALYTICS TO ROLE SYSADMIN;
GRANT USAGE ON ALL SCHEMAS IN DATABASE MARKET_ANALYTICS TO ROLE SYSADMIN;
GRANT SELECT ON ALL TABLES IN DATABASE MARKET_ANALYTICS TO ROLE SYSADMIN;

-- Show created objects
SHOW TABLES IN SCHEMA RAW;
SHOW TABLES IN SCHEMA ML;

SELECT 'Snowflake setup complete!' AS STATUS;